Qualification
DSI-Ville-Noumea/rundeck-springboot-jobs pull request #6
Opened 2020-08-28 02:41 UTC by feliixx

2020-09-04 04:06 UTC, feliixx commented
@nosskranitz testé en QUAL sur ce job: http://svq-rundeck0.site-mairie.noumea.nc:4440/project/DSI-Mairie/execution/show/11165

tout semble OK

2020-09-07 01:58 UTC, nosskranitz requested changes

2020-09-07 01:58 UTC, nosskranitz commented on rundeck_springboot_job_launcher.sh
> +     printf "\n\nErreur d'authentification sur le noeud %s\n\n" "$1"
renommer les variables plz

2020-09-07 04:29 UTC, feliixx commented on rundeck_springboot_job_launcher.sh
> +     printf "\n\nErreur d'authentification sur le noeud %s\n\n" "$1"
done

2020-09-07 04:30 UTC, feliixx commented
re-testé en QUAL avec les derniers changement, tout est OK

2020-09-11 00:19 UTC, nosskranitz approved these changes

2020-09-11 00:20 UTC, merged